config/routes.rb
Rails.application.routes.draw do
  resources :articals do
    get 'download', on: :collection
  end

  resources :reader_configs do
    post 'run', on: :member
  end
  resources :tasks, only: [:index, :show, :destroy]

  root 'reader_configs#index'
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :reader_config

  ERROR = 1
  SAVED = 2
  WAITING = 3
  RUNNING = 4
  ENDED = 5

  STATUS_NAME = {
    ERROR => '发生错误',
    SAVED => '排队中',
    WAITING => '等待中',
    RUNNING => '执行中',
    ENDED => '已完成'
  }

  def status_name
    STATUS_NAME[status]
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: '已删除' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

end

app/views/tasks/index.html.erb
<h3>采集任务列表</h3>

<% if @tasks.size > 0 %>
  <table class="table table-bordered table-striped table-hover">
    <tr>
      <th>任务ID</th>
      <th>采集配置</th>
      <th>状态</th>
      <th>操作</th>
    </tr>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.job_id %></td>
        <td><%= task.reader_config.name %></td>
        <td><%= task.status_name %></td>
        <td>
          <%= link_to '详情', task %>
          <%= link_to '删除', task, method: :delete, data: { confirm: '确定删除？' } %>
        </td>
      </tr>
      <% end %>
  </table>
<% else %>
  <ul class="list-group">
    <li class="list-group-item">没有符合条件的记录</li>
  </ul>
<% end %>

app/views/tasks/show.html.erb
<h3>任务详情</h3>

<p>
  <%= link_to '列表', tasks_path %>
  <%= link_to '删除', @task, method: :delete, data: { confirm: '确定删除？' } %>
</p>

<dl class="dl-horizontal">
  <dt>任务ID</dt>
  <dd><%= @task.job_id %></dd>

  <dt>采集配置</dt>
  <dd><%= @task.reader_config.name %></dd>

  <dt>状态</dt>
  <dd><%= @task.status_name %></dd>

  <% if @task.status == Task::ERROR %>
    <dt>错误</dt>
    <dd><%= @task.error %></dd>
  <% end %>
</dl>
<%= content_for :js do  %>
  <script type="text/javascript">
    $(function(){
      window.setTimeout(function(){
        location.href = location.href;
      }, 5000);
    });
  </script>
<% end %>