config/routes.rb
Rails.application.routes.draw do
  resources :articals do
    get 'download', on: :collection
  end

  resources :reader_configs do
    post 'run', on: :member
  end
  resources :tasks, only: [:index, :show, :destroy]

  root 'reader_configs#index'
end

app/models/artical.rb
class Artical < ActiveRecord::Base
  belongs_to :reader_config
  delegate :name, :to => :reader_config, :prefix => true
end

app/controllers/articals_controller.rb
class ArticalsController < ApplicationController
  before_action :find_articals, only: [:index, :download]
  before_action :set_artical, only: [:show, :edit, :update, :destroy]

  # GET /articals
  # GET /articals.json
  def index
    @articals = @articals.paginate(:page => params[:page], :per_page => 30)
  end

  def download
    send_file generate_file(@articals)
  end

  # GET /articals/1
  # GET /articals/1.json
  def show
  end

  # GET /articals/new
  def new
    @artical = Artical.new
  end

  # GET /articals/1/edit
  def edit
  end

  # POST /articals
  # POST /articals.json
  def create
    @artical = Artical.new(artical_params)

    respond_to do |format|
      if @artical.save
        format.html { redirect_to @artical, notice: 'Artical was successfully created.' }
        format.json { render :show, status: :created, location: @artical }
      else
        format.html { render :new }
        format.json { render json: @artical.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articals/1
  # PATCH/PUT /articals/1.json
  def update
    respond_to do |format|
      if @artical.update(artical_params)
        format.html { redirect_to @artical, notice: 'Artical was successfully updated.' }
        format.json { render :show, status: :ok, location: @artical }
      else
        format.html { render :edit }
        format.json { render json: @artical.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articals/1
  # DELETE /articals/1.json
  def destroy
    @artical.destroy
    respond_to do |format|
      format.html { redirect_to articals_url, notice: 'Artical was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_artical
      @artical = Artical.find(params[:id])
    end

    def search_params
      if params[:artical].present?
        params.require(:artical).permit(:title, :reader_config_id)
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def artical_params
      params.require(:artical).permit(:title, :url, :content, :reader_config_id, :images)
    end

    def find_articals
      conditions = search_params
      @artical = Artical.new(conditions)
      @articals = Artical.where('')
      if conditions
        if conditions[:title].present?
          conditions[:title].split(' ').each do |key_word|
            @articals = @articals.where("title like ?", "%#{key_word}%") if key_word.present?
          end
        end
        @articals = @articals.where(reader_config_id: conditions[:reader_config_id]) if conditions[:reader_config_id].present?
      end
    end

    def generate_file(articals)
      file_name = 'tmp/文章.txt'
      file = File.new(file_name, 'w')
      articals.each do  |artical|
        file.puts artical.title
        file.puts artical.content
        file.puts "*"*100
        file.puts "\n\n\n"
      end
      file.close
      file_name
    end
end

app/helpers/articals_helper.rb
module ArticalsHelper
end

app/views/articals/_form.html.erb
<%= form_for(@artical) do |f| %>
  <% if @artical.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@artical.errors.count, "error") %> prohibited this artical from being saved:</h2>

      <ul>
      <% @artical.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group container-fluid">
    <div class="row field-row">
      <div class="col-md-2 title"><%= f.label :title %></div>
      <div class="col-md-5"><%= f.text_field :title, class: 'form-control' %></div>
    </div>
    <div class="row field-row">
      <div class="col-md-2 title"><%= f.label :url %></div>
      <div class="col-md-5"><%= f.text_field :url, class: 'form-control', readonly: true %></div>
    </div>
    <div class="row field-row">
      <div class="col-md-2 title"><%= f.label :content %></div>
      <div class="col-md-5"><%= f.text_area :content, class: 'form-control', rows: 30, cols: 200 %></div>
    </div>
    <div class="row field-row">
      <div class="col-md-7 center"><%= f.submit "提交", class: "btn btn-primary" %></div>
    </div>
  </div>

<% end %>

app/views/articals/edit.html.erb
<h3>编辑文章</h3>

<p>
  <%= link_to '文章列表', articals_path %>
  <%= link_to '文章内容', @artical %>
</p>

<%= render 'form' %>

app/views/articals/index.html.erb
<h3>文章列表</h3>

<%= form_for @artical, method: :get, html: {class: 'form-inline search-form'} do |f| %>

  <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control' %>
      <%= f.label :reader_config_id %>
      <%= f.select :reader_config_id, ReaderConfig.all.collect {|config| [config.name, config.id]}, {include_blank: true}, {class: 'form-control'} %>
      <%= f.submit '搜索', class: "btn btn-primary" %>
      <%= link_to '导出', download_articals_path, class: "btn btn-primary btn-download" %>
  </div>

<% end %>

<ul class="list-group">
  <% @articals.each do |artical| %>
    <li class="list-group-item row item-row">
      <label class="title col-md-10 col-sm-10"><%= link_to artical.title, artical_path(artical), target: "_blank" %></label>
      <label class="options col-md-2 col-sm-2">
        <%= link_to '编辑', edit_artical_path(artical) %>
        <%= link_to '删除', artical, method: :delete, data: { confirm: '确定删除？' } %>
      </label>
    </li>
  <% end %>

  <% if @articals.size == 0 %>
    <li class="list-group-item">没有符合条件的记录</li>
  <% end %>
</ul>

<%= will_paginate @articals, previous_label: '上一页', next_label: '下一页' %>
<%= content_for :js do %>
<script type="text/javascript">
  $(function(){
    $('.btn-download').click(function(){
      $(this).parents('form').attr('action', '/download');
      return true;
    })
  })
</script>
<% end %>

app/views/articals/new.html.erb
<h3>新增文章</h3>

<p>
  <%= link_to '文章列表', articals_path %>
  <%= link_to '文章内容', @artical %>
</p>

<%= render 'form' %>

app/views/articals/show.html.erb
<h3><%= @artical.title %></h3>
<p>
  <%= link_to '文章列表', articals_path %>
  <%= link_to '编辑', edit_artical_path(@artical) %>
</p>

<p>
  <strong>Url:</strong>
  <%= @artical.url %>
</p>

<p>
  <strong>采集配置:</strong>
  <%= @artical.reader_config_name %>
</p>

<p>
  <strong>内容:</strong>
  <pre><%= @artical.content %></pre>
</p>

<p>
  <strong>图片:</strong>
  <% @artical.images.split(',').each do |img_path| %>
    <p><img src="/<%= img_path %>"></p>
  <% end %>
</p>