config/routes.rb
Rails.application.routes.draw do
  resources :articals do
    get 'download', on: :collection
  end

  resources :reader_configs do
    post 'run', on: :member
  end
  resources :tasks, only: [:index, :show, :destroy]

  root 'reader_configs#index'
end

app/models/reader_config.rb
class ReaderConfig < ActiveRecord::Base
end

app/controllers/reader_configs_controller.rb
class ReaderConfigsController < ApplicationController
  before_action :set_reader_config, only: [:show, :edit, :update, :destroy, :run]

  # GET /reader_configs
  # GET /reader_configs.json
  def index
    @reader_configs = ReaderConfig.all
  end

  # GET /reader_configs/1
  # GET /reader_configs/1.json
  def show
  end

  # GET /reader_configs/new
  def new
    @reader_config = ReaderConfig.new
  end

  # GET /reader_configs/1/edit
  def edit
  end

  # POST /reader_configs
  # POST /reader_configs.json
  def create
    @reader_config = ReaderConfig.new(reader_config_params)

    respond_to do |format|
      if @reader_config.save
        format.html { redirect_to reader_configs_path, notice: '采集配置创建成功' }
        format.json { render :show, status: :created, location: @reader_config }
      else
        format.html { render :new }
        format.json { render json: @reader_config.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reader_configs/1
  # PATCH/PUT /reader_configs/1.json
  def update
    respond_to do |format|
      if @reader_config.update(reader_config_params)
        format.html { redirect_to reader_configs_path, notice: '采集配置修改成功' }
        format.json { render :show, status: :ok, location: @reader_config }
      else
        format.html { render :edit }
        format.json { render json: @reader_config.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reader_configs/1
  # DELETE /reader_configs/1.json
  def destroy
    @reader_config.destroy
    respond_to do |format|
      format.html { redirect_to reader_configs_url, notice: '采集配置删除成功' }
      format.json { head :no_content }
    end
  end

  # POST /reader_config/1/run
  def run
    job = ArticalReadJob.perform_later(@reader_config)
    task = Task.create(job_id: job.job_id, reader_config_id: @reader_config.id, status: Task::WAITING)

    respond_to do |format|
      format.html { redirect_to task_url(task), notice: '采集任务已添加' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reader_config
      @reader_config = ReaderConfig.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reader_config_params
      params.require(:reader_config).permit(:name, :index_url, :index_pages, :index_next_page_selector, :index_next_page_content, :index_artical_link_selector,
       :artical_content_selectors, :artical_img_selectors, :artical_next_page_selector, :artical_next_page_content)
    end
end

app/helpers/reader_configs_helper.rb
module ReaderConfigsHelper
end

app/views/reader_configs/_form.html.erb
<%= form_for(@reader_config) do |f| %>
  <% if @reader_config.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reader_config.errors.count, "error") %> prohibited this reader_config from being saved:</h2>

      <ul>
      <% @reader_config.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group container-fluid">
    <div class="row field-row">
      <div class="col-md-2 title"><%= f.label :name %></div>
      <div class="col-md-5"><%= f.text_field :name, class: 'form-control' %></div>
    </div>

    <div class="row field-row">
      <div class="col-md-2 title"><%= f.label :index_url %></div>
      <div class="col-md-5"><%= f.text_field :index_url, class: 'form-control' %></div>
    </div>

    <div class="row field-row">
      <div class="col-md-2"><label>文章列表页</label></div>
    </div>

    <div class="row field-row">
      <div class="col-md-2 title"><%= f.label :index_artical_link_selector %></div>
      <div class="col-md-5"><%= f.text_field :index_artical_link_selector, class: 'form-control' %></div>
    </div>

    <div class="row field-row">
      <div class="col-md-2 title"><%= f.label :index_next_page_selector %></div>
      <div class="col-md-5"><%= f.text_field :index_next_page_selector, class: 'form-control' %></div>
    </div>

    <div class="row field-row">
      <div class="col-md-2 title"><%= f.label :index_next_page_content %></div>
      <div class="col-md-5"><%= f.text_field :index_next_page_content, class: 'form-control' %></div>
    </div>

    <div class="row field-row">
      <div class="col-md-2 title"><%= f.label :index_pages %></div>
      <div class="col-md-5"><%= f.number_field :index_pages, class: 'form-control' %></div>
    </div>

    <div class="row field-row">
      <div class="col-md-2"><label>文章详情页</label></div>
    </div>

    <div class="row field-row">
      <div class="col-md-2 title"><%= f.label :artical_content_selectors %></div>
      <div class="col-md-5"><%= f.text_field :artical_content_selectors, class: 'form-control' %></div>
    </div>

    <div class="row field-row">
      <div class="col-md-2 title"><%= f.label :artical_img_selectors %></div>
      <div class="col-md-5"><%= f.text_field :artical_img_selectors, class: 'form-control' %></div>
    </div>

    <div class="row field-row">
      <div class="col-md-2 title"><%= f.label :artical_next_page_selector %></div>
      <div class="col-md-5"><%= f.text_field :artical_next_page_selector, class: 'form-control' %></div>
    </div>

    <div class="row field-row">
      <div class="col-md-2 title"><%= f.label :artical_next_page_content %></div>
      <div class="col-md-5"><%= f.text_field :artical_next_page_content, class: 'form-control' %></div>
    </div>

    <div class="row field-row">
      <div class="col-md-2 title"><%= f.label :artical_pages %></div>
      <div class="col-md-5"><%= f.number_field :artical_pages, class: 'form-control' %></div>
    </div>

    <div class="row field-row">
      <div class="col-md-7 center"><%= f.submit "提交", class: "btn btn-primary" %></div>
    </div>
  </div>

<% end %>

app/views/reader_configs/edit.html.erb
<h3>编辑采集配置</h3>

<p>
  <%= link_to t('list'), reader_configs_path %>
</p>

<%= render 'form' %>

app/views/reader_configs/index.html.erb
<h3>配置列表</h3>

<p>
  <%= link_to '新建', new_reader_config_path %>
</p>

<ul class="list-group">
  <% @reader_configs.each do |reader_config| %>
    <li class="list-group-item row">
      <label class="title col-md-10 col-sm-10"><%= link_to reader_config.name, edit_reader_config_path(reader_config), target: "_blank" %></label>
      <label class="options col-md-2 col-sm-2">
        <%= link_to '采集', run_reader_config_path(reader_config), method: :post, data: { confirm: '确定开始采集？' } %>
        <%= link_to '编辑', edit_reader_config_path(reader_config) %>
        <%= link_to '删除', reader_config, method: :delete, data: { confirm: '确定删除？' } %>
      </label>
    </li>
  <% end %>

  <% if @reader_configs.size == 0 %>
    <li class="list-group-item">没有符合条件的记录</li>
  <% end %>
</ul>

app/views/reader_configs/new.html.erb
<h3>新建采集配置</h3>
<p>
  <%= link_to 'Back', reader_configs_path %>
</p>

<%= render 'form' %>

app/views/reader_configs/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @reader_config.name %>
</p>

<p>
  <strong>Index url:</strong>
  <%= @reader_config.index_url %>
</p>

<p>
  <strong>Index pages:</strong>
  <%= @reader_config.index_pages %>
</p>

<p>
  <strong>Index next page selector:</strong>
  <%= @reader_config.index_next_page_selector %>
</p>

<p>
  <strong>Index next page content:</strong>
  <%= @reader_config.index_next_page_content %>
</p>

<p>
  <strong>Index artical link selector:</strong>
  <%= @reader_config.index_artical_link_selector %>
</p>

<p>
  <strong>Artical content selectors:</strong>
  <%= @reader_config.artical_content_selectors %>
</p>

<p>
  <strong>Artical next page selector:</strong>
  <%= @reader_config.artical_next_page_selector %>
</p>

<p>
  <strong>Artical next page content:</strong>
  <%= @reader_config.artical_next_page_content %>
</p>

<%= link_to 'Edit', edit_reader_config_path(@reader_config) %> |
<%= link_to 'Back', reader_configs_path %>